### ISSUE TITLE
bug: HELM CHART Outline

### ISSUE THREAD

**Issue by JalisDiehl** [lrstanley/helm-charts#50]
### 🌧 Describe the problem

We are trying to deploy helm chart outline As-Is and we are facing some issues

> yarn run v1.22.22
$ node ./build/server/index.js
The environment variable MAXIMUM_IMPORT_SIZE is deprecated and will be removed in a future release. Use FILE_STORAGE_IMPORT_MAX_SIZE instead
{"label":"lifecycle","level":"info","message":"Note: Restricting process count to 1 due to use of collaborative service"}
{"error":"password authentication failed for user \"outline\"","level":"error","message":"Failed to connect to database","stack":"SequelizeConnectionError: password authentication failed for user \"outline\"\n at Client._connectionCallback (/opt/outline/node_modules/sequelize/lib/dialects/postgres/connection-manager.js:145:24)\n at Client._handleErrorWhileConnecting (/opt/outline/node_modules/pg/lib/client.js:327:19)\n at Client._handleErrorMessage (/opt/outline/node_modules/pg/lib/client.js:347:19)\n at Connection.emit (node:events:519:28)\n at Connection.emit (node:domain:488:12)\n at /opt/outline/node_modules/pg/lib/connection.js:117:12\n at Parser.parse (/opt/outline/node_modules/pg-protocol/dist/parser.js:36:17)\n at Socket.<anonymous> (/opt/outline/node_modules/pg-protocol/dist/index.js:11:42)\n at Socket.emit (node:events:519:28)\n at Socket.emit (node:domain:488:12)\n at addChunk (node:internal/streams/readable:559:12)\n at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)\n at Readable.push (node:internal/streams/readable:390:5)\n at TCP.onStreamRead (node:internal/stream_base_commons:191:23)"}
{"label":"lifecycle","level":"info","message":"Gracefully quitting"}
Done in 5.22s.

And I couldn't connect via shell on postgres

### ⛅ Expected behavior

It works

### 🔄 Minimal reproduction

helm install lrstanley/outline -f values.yaml

### 💠 Version: helm-charts

1.7.2

### 🖥 Version: Operating system

linux/ubuntu

### ⚙ Additional context

>     ingress:
>       enabled: true
>       ClassName: "nginx"
>       hosts:
>         - host: getoutline.xxx.network
>           paths:
>             - path: /
>               pathType: ImplementationSpecific
>       tls:
>        - secretName: getoutline-xxx-network-tls
>          hosts:
>            - getoutline.procer.network
>       annotations:
>         cert-manager.io/cluster-issuer: letsencrypt-infra
>     minio:
>       apiIngress:
>         hostname: s3-minio.xxx.network
>         ingressClassName: nginx

### 🤝 Requirements

- [X] I believe the problem I'm facing is a bug, and is not intended behavior. [Post here if you're not sure](../discussions/new?category=q-a).
- [X] I have confirmed that someone else has not [submitted a similar bug report](../labels/bug).

**Comment by lrstanley** [comment]
- has this worked successfully before for you?
- is the postgres statefulset healthy?
- does fully uninstalling (and making sure there are no left over secrets) and re-installing do anything? we auto-generate a one-time secret, and I think it can be finicky on first install. could also try overriding the password and turning off `postgresql.auth.generate`

**Comment by JalisDiehl** [comment]
Sure, I reinstall everything and I generate de secrets for postgres...

> 
>     database:
>       encryptionMode: "disable"
>       connectionPoolMin: "1"
>       connectionPoolMax: "100"
>     postgresql:
>       auth:
>         generate: false
>         enablePostgresUser: true
>     ingress:
>       enabled: true
>       ClassName: "nginx"
>       hosts:
>         - host: random-https
>           paths:
>             - path: /
>               pathType: ImplementationSpecific
>       tls:
>        - secretName: random-https-tls
>          hosts:
>            - random-https
>       annotations:
>         cert-manager.io/cluster-issuer: letsencrypt-infra
>     minio:
>       apiIngress:
>         hostname: random-https-s3
>         ingressClassName: nginx
>     dex:
>       enabled: true
>       ingress:
>         enabled: true
>         className: "nginx"
>         hosts:
>           - host: random-https
>             paths:
>               - path: /dex
>                 pathType: ImplementationSpecific
>         tls:
>         - secretName: random-https-tls
>           hosts:
>             - random-https
>         annotations:
>           cert-manager.io/cluster-issuer: letsencrypt-infra                
>       resources:
>         requests:
>           cpu: 25m
>           memory: 128Mi
>         limits:
>           memory: 128Mi
>       config:
>         storage:
>           type: memory
>         oauth2:
>           responseTypes: [ "code" ]
>           skipApprovalScreen: true
>           alwaysShowLoginScreen: false
>         connectors:
>           # github example -- create a Oauth App on GitHub and fill in the clientID and
>           # clientSecret below. redirectURI below should match "Authorization callback URL"
>           # in the GitHub OAuth App settings.
>           - type: gitlab
>             id: gitlab
>             name: GitLab
>             config:
>               # optional, default = https://gitlab.com
>               baseURL: https://gitlab.xxx.com.br
>               # Credentials can be string literals or pulled from the environment.
>               clientID: xxx
>               clientSecret: xxxx-xxxx
>               redirectURI: http://127.0.0.1:5556/dex/callback
>               groups:
>               - xxx
>               useLoginAsID: false

but now the issue it seems to be connection to database:

![image](https://github.com/user-attachments/assets/80d4fc6d-3d52-4e9a-89fc-127130f1e3df)
